### ISSUE TITLE
Not working on Prime Video.

### ISSUE THREAD

**Issue by silicon-sorcerer** [nolaneo/vemos#10]
I tried to use vemos on prime video, but the chrome extension icon never turned purple like it does on Netflix. I'm in North America.

**Comment by madrev** [comment]
+1, I think the issue here is that the watch URLs are different for amazon US vs. Europe. When I go to primevideo.com it tells me to "watch on Amazon". 

Annoyingly, the URL doesn't change when starting a video on amazon.com -- it just stays the same as whatever you were looking before, e.g. a listing: https://www.amazon.com/gp/video/detail/B07V2PG98H

This _may_ just be a matter of adding `amazon.com` to the list of launch domains, but not sure.

**Comment by nolaneo** [comment]
That _is_ annoying! Thanks for reporting @silicon-sorcerer & @madrev.  I've had a few others email about this too.

What I'll do is both add amazon.com, _and_ add optional permissions to access any URL. That should hopefully catch any more localized issues.

I wonder given that the URL doesn't change if there's some way to infer a canonical URL from the video on the page 🤔

**Comment by nolaneo** [comment]
I've submitted v0.0.3 to Google with amazon.com, primevideo.co.uk, and amazon.co.uk added to the permissions. It was insta rejected (as they always are 😩) so I've emailed them – they usually respond in 2-3 days or so.

If anyone knows someone in Google, I'd be very appreciative if they can let me know what I can do to stop being auto flagged.

**Comment by madrev** [comment]
I’ve got a friend on the Chrome team! I’ll ask her if she knows anything.

**Comment by nolaneo** [comment]
That'd be amazing! Thanks Maddie!

**Comment by nolaneo** [comment]
The latest version should now work wherever you need it to, so hopefully this issue is fixed for US Prime viewers.
